version: "3.1"
services:
    mongo-meta-db: 
        container_name: "mongo"
        image: "mongo:4.0.20"
        networks: 
            - bmat

    metadata_api:
        build: ./metadata_api
        container_name: "metadata_api"
        ports: 
            - "5000:5000"
        depends_on:
            - "mongo-meta-db"
        networks:
            - bmat

networks: 
    bmat: 
        driver: bridge 
