version: "3.1"
services:
    bmat-db: 
        container_name: "database" 
        image: "postgres:9.6.19-alpine" 
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_user=postgres
            - POSTGRES_PASSWORD=postgres
        networks: 
            - bmat 

    metadata_api:
        build: ./metadata_api
        container_name: "metadata_api"
        ports: 
            - "5000:5000"
        depends_on:
            - "bmat-db"
        networks:
            - bmat

    pgadmin: 
        container_name: "pgadmin4" 
        image: "thajeztah/pgadmin4" 
        ports: 
            - "5050:5050" 
        depends_on: 
            - "bmat-db" 
        networks: 
            - bmat 

networks: 
    bmat: 
        driver: bridge 
